apiVersion: v1
kind: ConfigMap
metadata:
  name: sosmed-configmap2
  namespace: staging
data:
  config.php: |
    <?php
    $db_host = "database.cft0sdpuovqh.ap-southeast-1.rds.amazonaws.com";
    $db_user = "devopscilsy";
    $db_pass = "1234567890";
    $db_name = "sosmed";
     try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>