apiVersion: v1
kind: Service
metadata:
  name: sosmed-configmap
  namespace: production
  labels:
    app: sosmed
spec:
  ports:
    - port: 80
  selector:
    app: sosmed-configmap
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-configmap
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sosmed-configmap
  template:
    metadata:
      labels:
        app: sosmed-configmap
    spec:
      volumes:
        - name: sosmed-configmap
          configMap:
            name: sosmed-configmap
      containers:
        - name: sosmed-configmap
          image: nazier1986/sosmed
          ports:
          - containerPort: 80
          volumeMounts:
          - name: sosmed-configmap
            mountPath: "/var/www/html/config.php"
            subPath: "config.php"

